version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8080:3000"
#    volumes:
#      - /usr/src/app/node_modules
#      - ./:/usr/src/app
    stdin_open: true

#  nginx:
#    restart: always
#    build:
#      dockerfile: ../Dockerfile
#      context: ./nginx
#    ports:
#      - "3000:80"