# Base image define
FROM node:14 as builder

WORKDIR '/usr/src/app'
# 종속성만 먼저 build : cache 사용
COPY package.json ./
RUN npm install

# 변경된 소스 적용
COPY ./ ./
# 시작시 실행될 명령어cd /

CMD ["npm", "run", "start"]